### PR TITLE
react-router

### PR DESCRIPTION
**Pull request by qstorey**
Reworked hn-clone to use react-router

### CODE REVIEW

**Comment by qstorey** [comment]
@Krylik please have a look at this PR.

A couple of questions regarding React and React-Router:
1. Is there a better way to structure my components?
2. I had to use absolute urls the root to get some things working, is this correct or am I missing something.

**Comment by Krylik** [comment]
@qstorey So the component structure looks fine, though really having only two components makes that pretty easy. I tend to favour having a pretty flat (directory/export) structure for my component files, as it seems to encourage reuse where possible.

Using absolute (root) urls is fine.

👍 🚢

**Comment by qstorey** [comment]
@Krylik awesome. Thanks.

**Comment by Krylik** [comment]
👏

**Pull request merged**
